### ISSUE TITLE
Adicionar lib no packagist.org

### ISSUE THREAD

**Issue by deyvisonrocha** [dev-newssystems/NSNFePHPLib#1]
Olá pessoal, tudo bem?

Gostaria de saber quais são os pacotes necessários para rodar a lib em um projeto?

Em breve mandarei um PR para adicionar o composer.json e torná-lo um package para introdução em qualquer projeto via composer.

**Comment by dev-nstecnologia** [comment]
Olá Deyvison, tudo ótimo e você?
É tudo nativo.
Show de bola, aguardamos teu PR e obrigado pela contribuição!
